### ISSUE TITLE
Recieving the following error when I try to copy/paste the "Basic Usage" file into Visual Studio Code

### ISSUE THREAD

**Issue by BigCharlestheGreat** [TheProtaganist/gpt-j#11]
Exception has occurred: JSONDecodeError
Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

  File "C:\Users\Lia\testing\test.py", line 28, in <module>
    res = simple_completion(prompt, length=Max, temp=temperature, top_p=top_probability, top_k=top_k, rep=rep)

**Comment by TheProtaganist** [comment]
I will update this as soon as I can
