### ISSUE TITLE
Could you open source the github?

### ISSUE THREAD

**Issue by MyUsernamee** [TheProtaganist/gpt-j#4]
Could you open source the package? It would be nice for users to be able to make modifications to the package that can then later be pushed to the main. Thank you in advance!

**Comment by TheProtaganist** [comment]
Sure... I'll do it later. I'm starting school tomorrow, But I'll open source by the end of the week. Take care

**Comment by TheProtaganist** [comment]
I hope this helps I just open-sourced it. Thank you for your interest in this project

**Comment by MyUsernamee** [comment]
Thank you!
